# Generated by Django 3.0.5 on 2021-10-19 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211017_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-pk',), 'verbose_name': 'Shopping cart', 'verbose_name_plural': 'Shopping carts'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('-pk',), 'verbose_name': 'Favourite recipe', 'verbose_name_plural': 'Favourite recipes'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('-pk',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pk',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-pk',), 'verbose_name': 'Ingredient for Recipe', 'verbose_name_plural': 'Ingredients for Recipe'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-pk',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='(in minutes)', validators=[django.core.validators.MinValueValidator(limit_value=1, message='You can not save time while cooking.')], verbose_name='cooking time'),
        ),
    ]
